<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.taskflow</groupId>
    <artifactId>taskflow</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <modules>
        <module>ApiGateway</module>
        <module>Task_service</module>
        <module>Eureka</module>
    </modules>

</project>