apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  EUREKA_URL: "http://eureka:8761/eureka"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  KEYCLOAK_URL: "http://keycloak:8080"
  MONGO_URI: "mongodb://mongo:27017/authdb"