apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
type: Opaque
stringData:
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"
  JWT_SECRET: "taskflow_secret_key_2024"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"