apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: taskflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: taskflow-api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: eureka.client.service-url.defaultZone
              value: "http://eureka:8761/eureka"
            - name: spring.security.oauth2.resourceserver.jwt.jwk-set-uri
              value: "http://keycloak:8080/realms/taskflow/protocol/openid-connect/certs"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: taskflow
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8085
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: taskflow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70